[config]
exclude-merge-commits=true
check-summary-length=false

[matchers]
simple="^(?:refactor|feature|test|fix|style|docs|chore)\\(.*?\\): .*?\n?$"
extended="^(?:refactor|feature|test|fix|style|docs|chore)\\(.*?\\): .*?\n(?:\n[^#].*?\n)*\n*(?:# ?.*?(?:\n|$))*"

[examples]
a_simple_commit="""
[refactor|feature|test|fix|style|docs|chore](module): A commit message
"""
an_extended_commit="""
[refactor|feature|test|fix|style|docs|chore](module): A commit message

first line

second line

and so on...

# commented line
# commented line
# commented line
#
"""